import type { MenuCategory, MenuItem } from './types';

/**
 * Full menu, ported 1:1 from the real Donisl Sommerkarte (see data/menu.json
 * for the raw source with the restaurant's own 23 section headings — this
 * file just regroups the same items into the app's 11 browsing categories).
 * Allergens are left empty on purpose: the restaurant has no verified
 * per-dish allergen data, and inventing any would violate the "never
 * invent" rule the AI assistant also follows.
 *
 * The "weekly" category holds the restaurant's Mittagsangebot — the five
 * Monday–Friday lunch specials. Each carries a `weekday` field (1=Mon … 5=Fri)
 * that drives the "today's lunch special" card on the home screen.
 *
 * The "oktoberfest" category is the restaurant's seasonal Wiesn "Schmankerl"
 * card (runs September/October), highlighted separately in the UI.
 */
export const menuItems: MenuItem[] = [
  // ================= weekly =================
  // -- Mittagsangebot / weekday lunch specials (Mon-Fri, served 12:00-15:30).
  //    `weekday` (1=Mon … 5=Fri) drives the "today's lunch" card on the home screen. --
  {
    id: 'lunch-monday-tagliatelle',
    categories: ['weekly'],
    name: 'Tagliatelle (Monday)',
    description: 'Monday lunch special, served 12:00–15:30. Tagliatelle with wild forest mushrooms and parsley.',
    price: 14.9,
    currency: 'EUR',
    weekday: 1,
    tags: ['lunch-special', 'vegetarian'],
    allergens: ["gluten","egg","dairy"],
    pairing: 'Grauburgunder (by the glass)',
    available: true,
  },
  {
    id: 'lunch-tuesday-bratengroestl',
    categories: ['weekly'],
    name: 'Donisl Bratengröstl (Tuesday)',
    image: '/assets/dishes/lunch-tuesday-bratengroestl.jpg',
    description: 'Tuesday lunch special, served 12:00–15:30. Mixed roast with white cabbage, potato dumpling and a fried egg.',
    price: 14.9,
    currency: 'EUR',
    weekday: 2,
    tags: ['lunch-special'],
    allergens: ["gluten","egg"],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'lunch-wednesday-leberkaese',
    categories: ['weekly'],
    name: 'Gebräunter Leberkäse (Wednesday)',
    description: 'Wednesday lunch special, served 12:00–15:30. Pan-browned Leberkäse with fried eggs and potato-cucumber salad.',
    price: 14.9,
    currency: 'EUR',
    weekday: 3,
    tags: ['lunch-special'],
    allergens: ["gluten","egg","mustard"],
    pairing: 'Münchner Hell',
    available: true,
  },
  {
    id: 'lunch-thursday-chicken-geschnetzeltes',
    categories: ['weekly'],
    name: 'Hähnchengeschnetzeltes (Thursday)',
    description: 'Thursday lunch special, served 12:00–15:30. Sliced chicken in mushroom sauce with herb spätzle.',
    price: 14.9,
    currency: 'EUR',
    weekday: 4,
    tags: ['lunch-special'],
    allergens: ["gluten","egg","dairy"],
    pairing: 'Münchner Radler',
    available: true,
  },
  {
    id: 'lunch-friday-fish-fillet',
    categories: ['weekly'],
    name: 'Gebackenes Fischfilet (Friday)',
    image: '/assets/dishes/lunch-friday-fish-fillet.jpg',
    description: "Friday lunch special, served 12:00–15:30. Fried catch of the day with remoulade and potato-cucumber salad.",
    price: 14.9,
    currency: 'EUR',
    weekday: 5,
    tags: ['lunch-special'],
    allergens: ["gluten","fish","egg"],
    pairing: 'Riesling Smoky Dry',
    available: true,
  },

  // ================= oktoberfest =================
  // -- Oktoberfest Schmankerl: the restaurant's Wiesn special card (runs Sept/Oct). --
  {
    id: 'oktoberfest-pumpkin-soup',
    categories: ['oktoberfest'],
    name: 'Kürbissamtsuppe',
    image: '/assets/dishes/oktoberfest-pumpkin-soup.jpg',
    description: 'Velvety pumpkin soup with Styrian pumpkin-seed oil and toasted seeds.',
    price: 8.9,
    currency: 'EUR',
    tags: ['seasonal', 'vegetarian'],
    allergens: ["dairy"],
    pairing: 'Weissweinschorle',
    available: true,
  },
  {
    id: 'oktoberfest-leberkas-burger',
    categories: ['oktoberfest'],
    name: 'Leberkas Burger',
    image: '/assets/dishes/oktoberfest-leberkas-burger.jpg',
    description: 'Leberkäse burger with a fried egg, French fries and herb sour cream.',
    price: 19.9,
    currency: 'EUR',
    tags: ['seasonal'],
    allergens: ["gluten","egg","dairy","mustard"],
    pairing: 'Oktoberfestbier',
    available: true,
  },
  {
    id: 'oktoberfest-bauernsalat',
    categories: ['oktoberfest'],
    name: 'Bauernsalat',
    description: 'Mixed leaf salad, potato salad and coleslaw with crispy pork-belly strips.',
    price: 19.9,
    currency: 'EUR',
    tags: ['seasonal'],
    allergens: ["egg","mustard"],
    pairing: 'Münchner Radler',
    available: true,
  },
  {
    id: 'oktoberfest-milchkalb-steak',
    categories: ['oktoberfest'],
    name: 'Steak vom Milchkalb',
    image: '/assets/dishes/oktoberfest-milchkalb-steak.jpg',
    description: 'Milk-fed veal steak with speck beans, red wine jus and creamed potatoes.',
    price: 36.9,
    currency: 'EUR',
    tags: ['seasonal', 'signature'],
    allergens: ["dairy"],
    pairing: 'Pinot Noir Ried Goldberg',
    available: true,
  },
  {
    id: 'oktoberfest-half-chicken',
    categories: ['oktoberfest'],
    name: 'Grilled half chicken',
    description: 'Grilled half chicken (½ Hendl) with potato-cucumber salad or French fries.',
    price: 19.9,
    currency: 'EUR',
    tags: ['seasonal'],
    allergens: ["gluten"],
    pairing: 'Hefeweizen (Yeast White)',
    available: true,
  },
  {
    id: 'oktoberfest-boiled-beef-fillet',
    categories: ['oktoberfest'],
    name: 'Boiled beef fillet',
    image: '/assets/dishes/oktoberfest-boiled-beef-fillet.jpeg',
    description: 'Boiled beef fillet with beef marrow bone, root vegetables, horseradish and rosemary potatoes.',
    price: 48.9,
    currency: 'EUR',
    tags: ['seasonal', 'signature'],
    allergens: ["celery"],
    pairing: 'Grüner Veltliner Ried Tenn DAC Reserve',
    available: true,
  },
  {
    id: 'oktoberfest-wiesn-reindl',
    categories: ['oktoberfest'],
    name: 'Wiesn Reindl (from 2 people)',
    image: '/assets/dishes/oktoberfest-wiesn-reindl.jpg',
    description: 'Sharing pan for the table: veal patty, schnitzel, bratwurst, pork knuckle and chicken with potato dumplings, sauerkraut and cheese spätzle. Priced per person, minimum two.',
    price: 36,
    currency: 'EUR',
    sizes: [{ label: 'per person', price: 36 }],
    tags: ['seasonal', 'sharing', 'signature'],
    allergens: ["gluten","egg","dairy","mustard"],
    pairing: 'Oktoberfestbier',
    available: true,
  },
  {
    id: 'oktoberfestbier',
    categories: ['oktoberfest'],
    name: 'Oktoberfestbier',
    image: '/assets/dishes/wiesnbier.jpg',
    imageFit: 'contain',
    description: 'The stronger, malty festival lager poured for Wiesn.',
    price: 6.4,
    currency: 'EUR',
    sizes: [
      { label: '0.5l', price: 6.4 },
      { label: '1.0l', price: 12.8 },
    ],
    tags: ['seasonal'],
    allergens: ["gluten"],
    pairing: 'Steak vom Milchkalb',
    available: true,
  },

  // ================= traditional =================
  // -- Traditional Bavarian Cuisine --
  {
    id: 'donisl-roasting-pan',
    categories: ['traditional'],
    name: 'Donisl roasting pan',
    image: '/assets/dishes/donisl-roasting-pan.jpg',
    description: 'Beef, duck, pork knuckle and sausages with red cabbage, potato dumplings and cheese spaetzle — for sharing.',
    price: 68,
    currency: 'EUR',
    sizes: [
      { label: '2 Pers.', price: 68 },
      { label: '4 Pers.', price: 124 },
    ],
    tags: ['sharing', 'signature'],
    allergens: ["gluten","egg","dairy"],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'roast-pork',
    categories: ['traditional'],
    name: 'Schweinebraten (roast pork)',
    image: '/assets/dishes/roast-pork.jpg',
    description: 'Bavarian pork shoulder and belly with crackling, natural gravy, potato dumplings and coleslaw.',
    price: 16.9,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 16.9 },
      { label: 'large', price: 20.9 },
    ],
    tags: ['hearty', 'signature'],
    allergens: ["gluten","egg"],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'schweinshaxe',
    categories: ['traditional'],
    name: 'Schweinshaxe (½)',
    image: '/assets/dishes/schweinshaxe.jpg',
    description: 'Crispy roasted half pork knuckle served with natural sauce, potato dumplings and coleslaw.',
    price: 24.9,
    currency: 'EUR',
    tags: ['hearty', 'signature'],
    allergens: ["gluten","egg"],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'wiener-schnitzel',
    categories: ['traditional'],
    name: 'Wiener Schnitzel',
    image: '/assets/dishes/wiener-schnitzel.jpg',
    description: 'Bavarian straw-fed pork schnitzel with fries or potato-cucumber salad and cranberries.',
    price: 19.6,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 19.6 },
      { label: 'large', price: 24.9 },
    ],
    tags: ['classic'],
    allergens: ["gluten","egg","dairy"],
    pairing: 'Riesling Easy-White or a Radler',
    available: true,
  },
  {
    id: 'farm-duck',
    categories: ['traditional'],
    name: 'Crispy Bavarian farm duck (1/4)',
    image: '/assets/dishes/farm-duck.jpg',
    description: 'Rosemary sauce, potato dumplings and red cabbage.',
    price: 24.9,
    currency: 'EUR',
    tags: ['hearty'],
    allergens: ["gluten","egg"],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'backhendl',
    categories: ['traditional'],
    name: 'Backhendl',
    image: '/assets/dishes/backhendl.jpg',
    description: 'Boneless breaded chicken leg with French fries or potato-cucumber salad.',
    price: 21.9,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten","egg","dairy"],
    pairing: 'Münchner Radler',
    available: true,
  },
  {
    id: 'duet-of-the-ox',
    categories: ['traditional'],
    name: 'Duet of the Ox',
    image: '/assets/dishes/duet-of-the-ox.jpg',
    description: 'Braised ox and grilled ox steak, red wine jus, red cabbage, creamed potatoes.',
    price: 31.9,
    currency: 'EUR',
    tags: ['hearty'],
    allergens: ["dairy","celery"],
    pairing: 'Black OX Cuvée',
    available: true,
  },
  {
    id: 'veal-meatballs',
    categories: ['traditional'],
    name: 'Kalbfleischpflanzerl (hand-pressed)',
    image: '/assets/dishes/veal-meatballs.jpg',
    description: 'Hand-pressed veal patties with dressed vegetables and rosemary potatoes.',
    price: 22.9,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten","egg"],
    pairing: 'Grauburgunder Tradition',
    available: true,
  },
  // -- Sausage Specialties --
  {
    id: 'white-sausage',
    categories: ['traditional', 'sausages'],
    name: 'White sausage (Kesselfrisch)',
    image: '/assets/dishes/white-sausage.jpg',
    description: 'Two pieces, served with pretzel and mustard.',
    price: 10.6,
    currency: 'EUR',
    tags: ['signature'],
    allergens: ["dairy","egg","mustard"],
    pairing: 'Hefeweizen (Yeast White)',
    available: true,
  },
  {
    id: 'white-sausage-piece',
    categories: ['traditional', 'sausages'],
    name: 'Piece of white sausage',
    description: 'A single white sausage.',
    price: 4.1,
    currency: 'EUR',
    tags: [],
    allergens: ["dairy","egg","mustard"],
    pairing: 'Hefeweizen (Yeast White)',
    available: true,
  },
  {
    id: 'currywurst',
    categories: ['traditional', 'sausages'],
    name: 'Currywurst',
    image: '/assets/dishes/currywurst.jpg',
    description: "Donisl's curry sausage sauce, served with French fries.",
    price: 15.9,
    currency: 'EUR',
    tags: ['classic'],
    allergens: ["gluten"],
    pairing: 'Hefeweizen wheat beer',
    available: true,
  },
  {
    id: 'bratwurstreindl',
    categories: ['traditional', 'sausages'],
    name: 'Bratwurstreindl',
    image: '/assets/dishes/bratwurstreindl.jpg',
    description: 'Pan of grilled sausages with sauerkraut or potato salad — a sharing portion.',
    price: 17.9,
    currency: 'EUR',
    sizes: [
      { label: '4 Würstl', price: 17.9 },
      { label: '8 Würstl', price: 29 },
      { label: '16 Würstl', price: 55 },
    ],
    tags: ['sharing'],
    allergens: ["gluten"],
    pairing: 'Russn (light Hefeweizen)',
    available: true,
  },
  // -- From the Grill --
  {
    id: 'rump-steak',
    categories: ['traditional'],
    name: 'Zwiebelrostbraten — rump steak',
    image: '/assets/dishes/rump-steak.jpg',
    description: 'Murnau beef with red wine and onion jus, fried onions, käsespätzle.',
    price: 33.9,
    currency: 'EUR',
    tags: [],
    allergens: ["dairy","gluten","egg"],
    pairing: 'Primitivo Puglia IGT',
    available: true,
  },
  {
    id: 'ribeye-300g',
    categories: ['traditional'],
    name: 'Ribeye 300 grams',
    image: '/assets/dishes/ribeye-300g.jpg',
    description: 'Fat cap from Murnau beef, café de paris sauce, grilled vegetables, potato gratin.',
    price: 39.9,
    currency: 'EUR',
    tags: [],
    allergens: ["dairy"],
    pairing: 'Brunello di Montalcino DOCG',
    available: true,
  },
  {
    id: 'deluxe-burger',
    categories: ['traditional'],
    name: 'Donisl Deluxe Burger',
    image: '/assets/dishes/deluxe-burger.jpg',
    description: '200g Werdenfelser beef, cheddar, lettuce, tomato, pickles, onions, homemade Donisl sauce. +3.90 with French fries.',
    price: 19.9,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten","dairy","egg","mustard"],
    pairing: 'Münchner Hell',
    available: true,
  },
  {
    id: 'zanderfilet',
    categories: ['traditional'],
    name: 'Zander fillet with potato crust',
    image: '/assets/dishes/zanderfilet.jpeg',
    description: 'Pike-perch fillet under a potato crust with colourful autumn vegetables and horseradish sauce.',
    price: 35.9,
    currency: 'EUR',
    tags: [],
    allergens: ["dairy","fish"],
    pairing: 'Sauvignon Blanc',
    available: true,
  },

  // ================= starters =================
  // -- Appetizers --
  {
    id: 'brotzeitbrettl',
    categories: ['starters'],
    name: 'Brotzeitbrettl',
    image: '/assets/dishes/brotzeitbrettl.jpg',
    description: "Farmer's smoked meats, bacon sausage, liverwurst, cold roast beef, O'gmachter, mountain cheese, horseradish, bread.",
    price: 24,
    currency: 'EUR',
    sizes: [
      { label: '2 Pers.', price: 24 },
      { label: '4 Pers.', price: 42 },
    ],
    tags: ['sharing'],
    allergens: ["gluten","dairy"],
    pairing: 'Hefeweizen (Yeast White)',
    available: true,
  },
  {
    id: 'donisl-4erlei',
    categories: ['starters'],
    name: 'Donisl "4erlei"',
    image: '/assets/dishes/donisl-4erlei.jpg',
    description: 'Hummus, made cheese, salted butter and herbed sour cream, served with a bread basket.',
    price: 11,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["gluten","dairy","sesame"],
    pairing: 'Weissweinschorle',
    available: true,
  },
  {
    id: 'beef-tartare',
    categories: ['starters'],
    name: 'Bavarian beef tartare',
    image: '/assets/dishes/beef-tartare.jpg',
    description: 'Truffle cream, baked organic egg.',
    price: 13.9,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 13.9 },
      { label: 'large', price: 21.9 },
    ],
    tags: [],
    allergens: ["egg","dairy"],
    pairing: 'Pinot Noir Ried Goldberg',
    available: true,
  },
  {
    id: 'ogmachter-kas',
    categories: ['starters'],
    name: "O'gmachter Kas",
    image: '/assets/dishes/ogmachter-kas.webp',
    description: 'Creamy cheese with onion rings, radishes, lettuce and berries.',
    price: 14.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["dairy"],
    pairing: 'Münchner Radler',
    available: true,
  },
  {
    id: 'sausage-salad',
    categories: ['starters'],
    name: 'Sausage salad from Regensburg',
    description: 'House dressing, onion rings, pickle, tomato, berry (+1.90 with strips of mountain cheese).',
    price: 17.8,
    currency: 'EUR',
    tags: [],
    allergens: ["dairy","egg"],
    pairing: 'Russn',
    available: true,
  },
  {
    id: 'donisl-salad',
    categories: ['starters'],
    name: 'Donisl Salad',
    image: '/assets/dishes/donisl-salad.jpg',
    description: 'Leafy greens, tomato, cucumber, house dressing, seeds and croutons.',
    price: 6.9,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 6.9 },
      { label: 'large', price: 12.9 },
    ],
    tags: ['vegetarian'],
    allergens: ["gluten","egg"],
    pairing: 'Weissweinschorle',
    available: true,
  },
  {
    id: 'bread-basket',
    categories: ['starters'],
    name: 'Bread basket',
    image: '/assets/dishes/bread-basket.jpg',
    description: 'Fresh bread basket.',
    price: 4.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["gluten"],
    pairing: 'Münchner Hell',
    available: true,
  },
  {
    id: 'brezn',
    categories: ['starters'],
    name: 'Brezn',
    image: '/assets/dishes/brezn.jpg',
    description: 'Bavarian pretzel.',
    price: 2.4,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["gluten"],
    pairing: 'Münchner Hell',
    available: true,
  },
  // -- From the Soup Kettle --
  {
    id: 'oxen-consomme',
    categories: ['starters'],
    name: 'Oxen consommé',
    image: '/assets/dishes/oxen-consomme.webp',
    description: 'Clear beef broth with liver dumplings or pancake strips, vegetables and chives.',
    price: 7.9,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten","egg"],
    pairing: 'Weissweinschorle',
    available: true,
  },
  // -- Extra Side Dishes --
  {
    id: 'classic-sides',
    categories: ['starters'],
    name: 'Classic side dish',
    image: '/assets/dishes/classic-sides.jpeg',
    description: 'Sauerkraut, red cabbage, bacon and cabbage salad, creamy potatoes, potato dumplings, small roasted potatoes, spätzle or French fries — each.',
    price: 5.6,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten","egg"],
    pairing: 'Münchner Hell',
    available: true,
  },
  {
    id: 'vegetable-sides',
    categories: ['starters'],
    name: 'Vegetable side dish',
    description: 'Vegetable side dish or potato and cucumber salad — each.',
    price: 5.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["egg"],
    pairing: 'Weissweinschorle',
    available: true,
  },

  // ================= vegan =================
  {
    id: 'power-bowl',
    categories: ['vegan'],
    name: 'Donisl Power Bowl',
    description: 'Fragrant rice, avocado, edamame, chickpeas, carrots, tomato, cucumber, peanuts, orange-mint-lime dressing.',
    price: 21.9,
    currency: 'EUR',
    sizes: [
      { label: 'with chicken', price: 21.9 },
      { label: 'with cured salmon', price: 22.9 },
      { label: 'with goat cheese', price: 22.9 },
    ],
    tags: ['bowl', 'signature'],
    allergens: ["peanuts","soy"],
    pairing: 'Sauvignon Blanc Reserve -S-',
    available: true,
  },
  {
    id: 'kaesespaetzle',
    categories: ['vegan'],
    name: 'Käsespätzle',
    image: '/assets/dishes/kaesespaetzle.jpg',
    description: 'Cheese spätzle with onion rings.',
    price: 14.9,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 14.9 },
      { label: 'large', price: 18.9 },
    ],
    tags: ['vegetarian'],
    allergens: ["gluten","egg","dairy"],
    pairing: 'Münchner Dunkel or a full-bodied white wine',
    available: true,
  },
  {
    id: 'linguine-truffles',
    categories: ['vegan'],
    name: 'Linguine with truffles',
    image: '/assets/dishes/linguine-truffles.jpg',
    description: 'Pasta with baby spinach and winter truffle.',
    price: 22.9,
    currency: 'EUR',
    tags: ['vegan'],
    allergens: ["gluten","egg"],
    pairing: 'Chardonnay (by the glass)',
    available: true,
  },

  // ================= desserts =================
  {
    id: 'creme-brulee',
    categories: ['desserts'],
    name: 'Crème brûlée',
    image: '/assets/dishes/creme-brulee.jpg',
    description: 'Served with sorbet and berries.',
    price: 12.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["dairy","egg"],
    pairing: 'Rieslaner Auslese dessert wine',
    available: true,
  },
  {
    id: 'kaiserschmarrn',
    categories: ['desserts'],
    name: 'Kaiserschmarrn (large)',
    image: '/assets/dishes/kaiserschmarrn.jpg',
    description: 'Raisins, butter, sugar and caramelized almonds, served with applesauce — ideal for sharing.',
    price: 15.6,
    currency: 'EUR',
    tags: ['vegetarian', 'sharing', 'signature'],
    allergens: ["gluten","dairy","egg","nuts"],
    pairing: 'Rieslaner Auslese dessert wine',
    available: true,
  },
  {
    id: 'kirschmichl',
    categories: ['desserts'],
    name: 'Kirschmichl',
    image: '/assets/dishes/kirschmichl.jpg',
    description: 'Warm cherry cake served with custard.',
    price: 9.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["gluten","dairy","egg"],
    pairing: 'Rieslaner Auslese',
    available: true,
  },
  {
    id: 'apple-strudel',
    categories: ['desserts'],
    name: 'Apple strudel',
    image: '/assets/dishes/apple-strudel.jpg',
    description: 'Classic apple strudel served with custard.',
    price: 9.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["gluten","dairy","egg"],
    pairing: 'Milchkaffee',
    available: true,
  },

  // ================= beer =================
  {
    id: 'muenchner-hell',
    categories: ['beer'],
    name: 'Münchner Hell',
    image: '/assets/dishes/muenchner-hell.webp',
    imageFit: 'contain',
    description: 'Bottom-fermented, delicately bitter hop note, slightly malty. 5.0% vol.',
    price: 4.7,
    currency: 'EUR',
    sizes: [
      { label: '0.35l', price: 4.7 },
      { label: '0.5l', price: 5.4 },
      { label: '1.0l', price: 10.8 },
    ],
    tags: [],
    allergens: ["gluten"],
    pairing: 'Wiener Schnitzel',
    available: true,
  },
  {
    id: 'beer-light-alcohol-free',
    categories: ['beer'],
    name: 'Light Alcohol-Free',
    image: '/assets/dishes/beer-light-alcohol-free.jpg',
    imageFit: 'contain',
    description: 'Naturally cloudy, caramel and honey notes. <0.5% vol.',
    price: 5.4,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: ["gluten"],
    pairing: 'Brotzeitbrettl',
    available: true,
  },
  {
    id: 'muenchner-radler',
    categories: ['beer'],
    name: 'Münchner Radler',
    image: '/assets/dishes/muenchner-radler.png',
    imageFit: 'contain',
    description: 'Munich Helles with fine lemonade, not too sweet.',
    price: 5.4,
    currency: 'EUR',
    tags: ['light'],
    allergens: ["gluten"],
    pairing: 'Donisl Salad',
    available: true,
  },
  {
    id: 'muenchner-dunkel',
    categories: ['beer'],
    name: 'Münchner Dunkel',
    image: '/assets/dishes/muenchner-dunkel.png',
    imageFit: 'contain',
    description: 'Delicately bitter, roasted malt with caramel and candied fruit notes. 5.0% vol.',
    price: 6.2,
    currency: 'EUR',
    tags: ['hearty'],
    allergens: ["gluten"],
    pairing: 'Schweinshaxe',
    available: true,
  },
  {
    id: 'hefeweizen',
    categories: ['beer'],
    name: 'Hefeweizen (Yeast White)',
    image: '/assets/dishes/hefeweizen.webp',
    imageFit: 'contain',
    description: 'Top-fermented wheat beer with banana and honey notes.',
    price: 6.2,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten"],
    pairing: 'White sausage (Kesselfrisch)',
    available: true,
  },
  {
    id: 'russn',
    categories: ['beer'],
    name: 'Russn',
    image: '/assets/dishes/russn.webp',
    imageFit: 'contain',
    description: 'Hefeweizen with delicate lemonade, not too sweet.',
    price: 6.2,
    currency: 'EUR',
    tags: ['light'],
    allergens: ["gluten"],
    pairing: 'Bratwurstreindl',
    available: true,
  },
  {
    id: 'cola-wheat',
    categories: ['beer'],
    name: 'Cola Wheat',
    image: '/assets/dishes/cola-wheat.webp',
    imageFit: 'contain',
    description: 'Hefeweizen with Coca-Cola.',
    price: 6.2,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten"],
    pairing: 'Currywurst',
    available: true,
  },
  {
    id: 'non-alcoholic-wheat',
    categories: ['beer'],
    name: 'Paulaner alcohol-free wheat beer',
    image: '/assets/dishes/non-alcoholic-wheat.webp',
    imageFit: 'contain',
    description: 'Gently dealcoholized after full maturation, keeps its aroma.',
    price: 6.2,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: ["gluten"],
    pairing: 'Backhendl',
    available: true,
  },
  {
    id: 'salvator',
    categories: ['beer'],
    name: 'Salvator',
    image: '/assets/dishes/salvator.png',
    imageFit: 'contain',
    description: 'Strong beer (Starkbier), seasonal — available February/March. 0.5l.',
    price: 6.4,
    currency: 'EUR',
    tags: ['seasonal', 'strong'],
    allergens: ["gluten"],
    pairing: 'Duet of the Ox',
    available: true,
  },
  {
    id: 'kellerbier',
    categories: ['beer'],
    name: 'Kellerbier',
    image: '/assets/dishes/kellerbier.jpg',
    imageFit: 'contain',
    description: 'Seasonal — available June/July/August (Sommerzeit). 0.5l.',
    price: 6.1,
    currency: 'EUR',
    tags: ['seasonal'],
    allergens: ["gluten"],
    pairing: 'Brotzeitbrettl',
    available: true,
  },
  {
    id: 'wiesnbier',
    categories: ['beer'],
    name: 'Wiesnbier',
    image: '/assets/dishes/wiesnbier.jpg',
    imageFit: 'contain',
    description: 'Oktoberfest beer, seasonal — available September/October.',
    price: 6.4,
    currency: 'EUR',
    sizes: [
      { label: '0.5l', price: 6.4 },
      { label: '1.0l', price: 12.8 },
    ],
    tags: ['seasonal'],
    allergens: ["gluten"],
    pairing: 'Donisl roasting pan',
    available: true,
  },

  // ================= wine =================
  // -- Wine from the Barrel (by the glass) --
  {
    id: 'weissweinschorle',
    categories: ['wine'],
    name: 'Weissweinschorle',
    description: 'White wine spritzer. 0.3l.',
    price: 7,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: ["sulphites"],
    pairing: 'Donisl Salad',
    available: true,
  },
  {
    id: 'pinot-gris-glass',
    categories: ['wine'],
    name: 'Grauburgunder (by the glass)',
    description: 'Hirschmüller Winery, Württemberg — light, easy-drinking.',
    price: 6,
    currency: 'EUR',
    sizes: [
      { label: '0.1l', price: 6 },
      { label: '0.2l', price: 9 },
    ],
    tags: ['white', 'by-glass'],
    allergens: ["sulphites"],
    pairing: 'Kalbfleischpflanzerl (hand-pressed)',
    available: true,
  },
  {
    id: 'primitivo-glass',
    categories: ['wine'],
    name: 'Primitivo Puglia IGT (by the glass)',
    description: 'Sir of the Faun, Puglia — dark berries, cherry, subtle spice.',
    price: 6,
    currency: 'EUR',
    sizes: [
      { label: '0.1l', price: 6 },
      { label: '0.2l', price: 9 },
    ],
    tags: ['red', 'by-glass'],
    allergens: ["sulphites"],
    pairing: 'Schweinebraten (roast pork)',
    available: true,
  },
  {
    id: 'prodry-frizzante',
    categories: ['wine'],
    name: 'Prodry Frizzante',
    description: 'Motelvini, Veneto, Italy. 0.1l.',
    price: 5.5,
    currency: 'EUR',
    tags: ['sparkling', 'by-glass'],
    allergens: ["sulphites"],
    pairing: 'Brotzeitbrettl',
    available: true,
  },
  // -- Champagne & Sparkling --
  {
    id: 'paul-michel-champagne',
    categories: ['wine'],
    name: 'Paul Michel',
    description: 'Champagne Premier Cru, Champagne, France. 0.75l bottle.',
    price: 120,
    currency: 'EUR',
    tags: ['sparkling', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Oxen consommé',
    available: true,
  },
  {
    id: 'taittinger-rose',
    categories: ['wine'],
    name: 'Taittinger Prestige Rosé Brut',
    description: 'Champagne Taittinger, France. 0.75l bottle.',
    price: 145,
    currency: 'EUR',
    tags: ['sparkling', 'rose', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Donisl "4erlei"',
    available: true,
  },
  {
    id: 'valdo-prosecco',
    categories: ['wine'],
    name: 'Valdo Prosecco Superiore DOCG',
    description: 'Valdo, Veneto — classic Italian sparkling wine. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['sparkling', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Donisl Salad',
    available: true,
  },
  {
    id: 'winzersekt',
    categories: ['wine'],
    name: 'Winzersekt',
    description: 'Pfaffmann Winery, Palatinate, Germany. 0.75l bottle.',
    price: 45,
    currency: 'EUR',
    tags: ['sparkling', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Oxen consommé',
    available: true,
  },
  // -- White Wine --
  {
    id: 'chardonnay-bottle',
    categories: ['wine'],
    name: 'Chardonnay',
    description: 'Hirschmüller Winery, Württemberg — passion fruit, mango, pineapple. 0.75l bottle.',
    price: 34,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Käsespätzle',
    available: true,
  },
  {
    id: 'chardonnay-glass',
    categories: ['wine'],
    name: 'Chardonnay (by the glass)',
    description: 'Hirschmüller Winery, Württemberg. 0.1l.',
    price: 6,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: [],
    pairing: 'Linguine with truffles',
    available: true,
  },
  {
    id: 'chardonnay-macon-ige',
    categories: ['wine'],
    name: 'Chardonnay Mâcon-Igé La Cra',
    description: 'Domaine Fichet, Burgundy — apple, pear, white peach, subtle minerality. 0.75l bottle.',
    price: 69,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Käsespätzle',
    available: true,
  },
  {
    id: 'pinot-gris-tradition',
    categories: ['wine'],
    name: 'Grauburgunder Tradition',
    description: 'Bott Frères Winery, Burgundy — apricot, Viennese apple, hazelnut, subtle smoke. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Kalbfleischpflanzerl (hand-pressed)',
    available: true,
  },
  {
    id: 'pinot-gris-oetinger',
    categories: ['wine'],
    name: 'Grauburgunder',
    description: 'Oetinger Winery, Rheingau — ripe pear, yellow apple, hint of almond. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Backhendl',
    available: true,
  },
  {
    id: 'pinot-gris-reserve-pauline',
    categories: ['wine'],
    name: 'Grauburgunder Reserve Pauline',
    description: 'Pfaffmann Winery, Palatinate — pear, pineapple, nectarine, lemongrass, floral. 0.75l bottle.',
    price: 56,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'O\'gmachter Kas',
    available: true,
  },
  {
    id: 'pinot-blanc-grand-reserve',
    categories: ['wine'],
    name: 'Weißburgunder Große Reserve',
    description: 'Taubenschuss Winery, Austrian Weinviertel — melon, hazelnut, hay, caramel. 0.75l bottle.',
    price: 79,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Donisl "4erlei"',
    available: true,
  },
  {
    id: 'trebbiano-di-lugana',
    categories: ['wine'],
    name: 'Trebbiano di Lugana',
    description: 'Zenato Winery, Veneto, Italy — fresh acidity, mineral, citrus, green apple, pear. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Sausage salad from Regensburg',
    available: true,
  },
  {
    id: 'lugana-glass',
    categories: ['wine'],
    name: 'Lugana (by the glass)',
    description: 'Zenato Winery, Veneto, Italy. 0.1l.',
    price: 6.5,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: [],
    pairing: 'Zander fillet with potato crust',
    available: true,
  },
  {
    id: 'riesling-easy-white',
    categories: ['wine'],
    name: 'Riesling Easy-White',
    description: 'Oetinger Winery, Rheingau — lime, apple, white peach, ideal aperitif. 0.75l bottle.',
    price: 33,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Wiener Schnitzel',
    available: true,
  },
  {
    id: 'riesling-gottloos',
    categories: ['wine'],
    name: 'Riesling Gottloos',
    description: 'Dr. Loosen Winery, Mosel — citrus, apple, elegant minerality. 0.75l bottle.',
    price: 42,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Wiener Schnitzel',
    available: true,
  },
  {
    id: 'riesling-heiligenstein',
    categories: ['wine'],
    name: 'Riesling Ried Heiligenstein',
    description: 'Bründlmayer Winery, Langenlois, Kamptal, Austria — fresh citrus, apple, herbal spice. 0.75l bottle.',
    price: 98,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Donisl Salad',
    available: true,
  },
  {
    id: 'riesling-smoky-dry',
    categories: ['wine'],
    name: 'Riesling Smoky Dry',
    description: 'Weingut Oetinger, Rheingau — smoky minerality, juicy apple, citrus. 0.75l bottle.',
    price: 49,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Currywurst',
    available: true,
  },
  {
    id: 'riesling-bright-side-of-life',
    categories: ['wine'],
    name: 'Riesling Refill "Bright side of life" 2024',
    description: 'Stahl Winery, Franconia, Germany — fruity, fresh, uncomplicated. 0.75l bottle.',
    price: 29,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Gebackenes Fischfilet (Friday)',
    available: true,
  },
  {
    id: 'riesling-nachschlag-glass',
    categories: ['wine'],
    name: 'Riesling "Nachschlag – Bright Side of Life" 2024 (by the glass)',
    description: 'Stahl Winery, Franconia, Germany. 0.1l.',
    price: 5.5,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: [],
    pairing: 'Gebackenes Fischfilet (Friday)',
    available: true,
  },
  {
    id: 'sauvignon-blanc',
    categories: ['wine'],
    name: 'Sauvignon Blanc',
    description: 'Chateau de la Chaise, Loire — gooseberry, green apple, exotic fruit. 0.75l bottle.',
    price: 45,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Zander fillet with potato crust',
    available: true,
  },
  {
    id: 'sauvignon-blanc-reserve',
    categories: ['wine'],
    name: 'Sauvignon Blanc Reserve -S-',
    description: 'Taubenschuss Winery, Austrian Weinviertel — lime, gooseberry, exotic fruit. 0.75l bottle.',
    price: 58,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Donisl Power Bowl',
    available: true,
  },
  {
    id: 'silvaner-easy-white',
    categories: ['wine'],
    name: 'Silvaner Easy-White',
    description: 'Weingut am Stein, Franconia — green apple, pear, subtle herbs. 0.75l bottle.',
    price: 32,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Vegetable side dish',
    available: true,
  },
  {
    id: 'gruener-veltliner-tenn',
    categories: ['wine'],
    name: 'Grüner Veltliner Ried Tenn DAC Reserve',
    description: 'Taubenschuss Winery, Austrian Weinviertel — apple, white pepper, herbal spice. 0.75l bottle.',
    price: 54,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Lukewarm calf\'s head carpaccio',
    available: true,
  },
  // -- Large Bottles --
  {
    id: 'riesling-gottloos-3l',
    categories: ['wine'],
    name: 'Riesling Gottloos (large bottle)',
    description: 'Dr. Loosen Winery, Mosel. 3.0l bottle.',
    price: 168,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Wiener Schnitzel',
    available: true,
  },
  {
    id: 'gruener-veltliner-steinberg',
    categories: ['wine'],
    name: 'Grüner Veltliner Ried Steinberg',
    description: 'Karl Fritsch Winery, Burgenland, Austria. 1.5l bottle.',
    price: 120,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Käsespätzle',
    available: true,
  },
  {
    id: 'chardonnay-morillon',
    categories: ['wine'],
    name: 'Chardonnay Morillon Ried Flammberg',
    description: 'Lackner-Tinnacher Winery, Southern Styria, Austria. 1.5l bottle.',
    price: 160,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'O\'gmachter Kas',
    available: true,
  },
  {
    id: 'cuvee-adrian-sangiovese',
    categories: ['wine'],
    name: 'Cuvée Adrian Sangiovese 2021',
    description: 'Red cuvée, Toscana Rosso, Tuscany. 1.5l bottle.',
    price: 98,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Duet of the Ox',
    available: true,
  },
  // -- Red Wine --
  {
    id: 'primitivo-bottle',
    categories: ['wine'],
    name: 'Primitivo Puglia IGT',
    description: 'Barbanera Winery, Apulia, Italy — dark berries, cherry, subtle spice. 0.75l bottle.',
    price: 34,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Schweinebraten (roast pork)',
    available: true,
  },
  {
    id: 'herrgott-cuvee',
    categories: ['wine'],
    name: 'Herrgott Cuvée',
    description: 'Cabernet Sauvignon/Franc, Merlot, Weingut am Nil, Palatinate — cherries, red berries. 0.75l bottle.',
    price: 38,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Ribeye 300 grams',
    available: true,
  },
  {
    id: 'herrgott-cuvee-glass',
    categories: ['wine'],
    name: 'Herrgott Cuvée (by the glass)',
    description: 'Cabernet Sauvignon/Franc, Merlot, Weingut am Nil, Palatinate. 0.1l.',
    price: 6.5,
    currency: 'EUR',
    tags: ['red', 'by-glass'],
    allergens: [],
    pairing: 'Donisl Bratengröstl (Tuesday)',
    available: true,
  },
  {
    id: 'tuscany-red-cuvee',
    categories: ['wine'],
    name: 'Tuscany Red Cuvée',
    description: 'Duca di Salangane, Toscana — cherries, dark berries. 0.75l bottle.',
    price: 29,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Roast beef — rump steak',
    available: true,
  },
  {
    id: 'pinot-noir-goldberg',
    categories: ['wine'],
    name: 'Pinot Noir Ried Goldberg',
    description: 'Toni Hartl Winery, Burgenland — red berries, cherries, subtle spice. 0.75l bottle.',
    price: 79,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Steak vom Milchkalb',
    available: true,
  },
  {
    id: 'merlot',
    categories: ['wine'],
    name: 'Merlot',
    description: 'Chateau Gensac, Gascony — dark cherries, plums, spice. 0.75l bottle.',
    price: 42,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Veal meatballs',
    available: true,
  },
  {
    id: 'brunello-di-montalcino',
    categories: ['wine'],
    name: 'Brunello di Montalcino DOCG',
    description: 'Tenuta Corte Pavone Winery, Sangiovese, Tuscany — dark berry, cherry, chocolate. 0.75l bottle.',
    price: 135,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Ribeye 300 grams',
    available: true,
  },
  {
    id: 'black-ox-cuvee',
    categories: ['wine'],
    name: 'Black OX Cuvée',
    description: 'Cabernet Sauvignon, Dornfelder, Tempranillo, Weingut Lergenmüller, Palatinate — dark berries, cherry, spice. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Duet of the Ox',
    available: true,
  },
  // -- Rosé Wine --
  {
    id: 'rose-lime-stone',
    categories: ['wine'],
    name: 'Rosé Lime & Stone',
    description: 'Unger Winery, Lake Neusiedl — red berries, strawberry, raspberry, citrus. 0.75l bottle.',
    price: 36,
    currency: 'EUR',
    tags: ['rose', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Donisl Salad',
    available: true,
  },
  {
    id: 'torres-natureo',
    categories: ['wine'],
    name: 'Torres Natureo (alcohol-free)',
    description: 'Miguel Torres, Vilafranca del Penedès — citrus, apple, light. 0.75l bottle.',
    price: 29,
    currency: 'EUR',
    tags: ['rose', 'bottle', 'non-alcoholic'],
    allergens: ["sulphites"],
    pairing: 'Donisl Salad',
    available: true,
  },
  // -- Dessert Wine --
  {
    id: 'rieslaner-auslese',
    categories: ['wine'],
    name: 'Rieslaner Auslese',
    description: 'Juliusspital Winery, Franconia — dessert wine. 0.5l bottle.',
    price: 58,
    currency: 'EUR',
    tags: ['dessert-wine', 'bottle'],
    allergens: ["sulphites"],
    pairing: 'Kaiserschmarrn or Crème brûlée',
    available: true,
  },

  // ================= aperitif =================
  {
    id: 'aperol-spritz',
    categories: ['aperitif'],
    name: 'Aperol Spritz',
    image: '/assets/dishes/aperol-spritz.jpg',
    imageFit: 'contain',
    description: 'Classic Italian aperitif. 0.2l.',
    price: 8.9,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: ["sulphites"],
    pairing: 'Brotzeitbrettl',
    available: true,
  },
  {
    id: 'hugo',
    categories: ['aperitif'],
    name: 'Hugo',
    image: '/assets/dishes/hugo.jpg',
    imageFit: 'contain',
    description: 'Elderflower spritz. 0.2l.',
    price: 8.9,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: ["sulphites"],
    pairing: 'Bread basket',
    available: true,
  },
  {
    id: 'campari-soda',
    categories: ['aperitif'],
    name: 'Campari Soda',
    image: '/assets/dishes/campari-soda.jpg',
    description: '0.2l.',
    price: 6,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: [],
    pairing: 'Brezn',
    available: true,
  },
  {
    id: 'campari-orange',
    categories: ['aperitif'],
    name: 'Campari Orange',
    image: '/assets/dishes/campari-orange.jpg',
    imageFit: 'contain',
    description: '0.2l.',
    price: 8.4,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: [],
    pairing: 'Donisl "4erlei"',
    available: true,
  },
  {
    id: 'sanbitter',
    categories: ['aperitif'],
    name: 'Sanbitter',
    image: '/assets/dishes/sanbitter.jpg',
    description: 'Alcohol-free bitter aperitif. 0.2l.',
    price: 8,
    currency: 'EUR',
    tags: ['aperitif', 'non-alcoholic'],
    allergens: [],
    pairing: 'Oxen consommé',
    available: true,
  },

  // ================= spirits =================
  {
    id: 'nut-in-a-bottle',
    categories: ['spirits'],
    name: 'Nut (in a bottle)',
    description: '2cl.',
    price: 4,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: ["nuts"],
    pairing: 'Kirschmichl',
    available: true,
  },
  {
    id: 'ruescherl',
    categories: ['spirits'],
    name: 'Rüscherl',
    description: '13cl.',
    price: 5,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Apple strudel',
    available: true,
  },
  {
    id: 'hirschkuss',
    categories: ['spirits'],
    name: 'Hirschkuss',
    image: '/assets/dishes/hirschkuss.jpg',
    imageFit: 'contain',
    description: '38% vol., swing-top bottle, 4cl.',
    price: 7,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Kaiserschmarrn (large)',
    available: true,
  },
  {
    id: 'vodka-redbull',
    categories: ['spirits'],
    name: 'Vodka RedBull',
    image: '/assets/dishes/vodka-redbull.jpg',
    description: '0.27l.',
    price: 9.5,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Donisl Deluxe Burger',
    available: true,
  },
  {
    id: 'williams-christ-pear',
    categories: ['spirits'],
    name: 'Williams Christ pear',
    image: '/assets/dishes/williams-christ-pear.png',
    imageFit: 'contain',
    description: '40% vol. Edelbrand, Sigi Herzog Distillate. 2cl.',
    price: 4.9,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Apple strudel',
    available: true,
  },
  {
    id: 'farm-fruit-growers',
    categories: ['spirits'],
    name: 'Farm fruit growers',
    description: 'Linster fine fruit distillery, aged 1 year in oak barrels. 2cl.',
    price: 4.6,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Kirschmichl',
    available: true,
  },
  {
    id: 'feiner-mirabell',
    categories: ['spirits'],
    name: 'Feiner Mirabell',
    image: '/assets/dishes/feiner-mirabell.jpg',
    imageFit: 'contain',
    description: 'Linster fine fruit distillery, ripe apricot flavor. 2cl.',
    price: 5.6,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Crème brûlée',
    available: true,
  },
  {
    id: 'enzian-gentian-brandy',
    categories: ['spirits'],
    name: 'Enzian Gentian Brandy',
    image: '/assets/dishes/enzian-gentian-brandy.webp',
    imageFit: 'contain',
    description: 'Wilhelm Marx Fine Spirits Manufactory. 2cl.',
    price: 7.9,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Schweinshaxe',
    available: true,
  },
  {
    id: 'raspberry-pulp-brandy',
    categories: ['spirits'],
    name: 'Raspberry pulp brandy',
    image: '/assets/dishes/raspberry-pulp-brandy.png',
    imageFit: 'contain',
    description: '40% vol. Edelmanufaktur Wilhelm Marx. 2cl.',
    price: 7.9,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Kaiserschmarrn (large)',
    available: true,
  },
  {
    id: 'grappa-chardonnay',
    categories: ['spirits'],
    name: 'Grappa from Chardonnay',
    image: '/assets/dishes/grappa-chardonnay.jpg',
    imageFit: 'contain',
    description: 'Grandfather. 2cl.',
    price: 5.6,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    pairing: 'Crème brûlée',
    available: true,
  },

  // ================= drinks (alcohol-free & coffee) =================
  {
    id: 'paulaner-spezi',
    categories: ['drinks'],
    name: 'Paulaner Spezi',
    image: '/assets/dishes/paulaner-spezi.png',
    imageFit: 'contain',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Currywurst',
    available: true,
  },
  {
    id: 'coca-cola',
    categories: ['drinks'],
    name: 'Coca-Cola',
    image: '/assets/dishes/coca-cola.jpg',
    imageFit: 'contain',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: '2 Rostbratwürstl',
    available: true,
  },
  {
    id: 'coca-cola-zero',
    categories: ['drinks'],
    name: 'Coca-Cola Zero',
    image: '/assets/dishes/coca-cola-zero.webp',
    imageFit: 'contain',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Portion of French Fries',
    available: true,
  },
  {
    id: 'paulaner-lemonade',
    categories: ['drinks'],
    name: 'Paulaner Lemonade',
    image: '/assets/dishes/paulaner-lemonade.jpg',
    imageFit: 'contain',
    description: '0.33l.',
    price: 4.2,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Kässpatzn',
    available: true,
  },
  {
    id: 'paulaner-orange-lemonade',
    categories: ['drinks'],
    name: 'Paulaner Orange Lemonade',
    image: '/assets/dishes/paulaner-orange-lemonade.webp',
    imageFit: 'contain',
    description: '0.33l.',
    price: 4.2,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Potato dumplings',
    available: true,
  },
  {
    id: 'tonic',
    categories: ['drinks'],
    name: 'Tonic',
    image: '/assets/dishes/tonic.jpg',
    imageFit: 'contain',
    description: '0.2l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Brotzeitbrettl',
    available: true,
  },
  {
    id: 'red-bull',
    categories: ['drinks'],
    name: 'Red Bull',
    image: '/assets/dishes/red-bull.jpg',
    imageFit: 'contain',
    description: '0.25l.',
    price: 5.5,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Donisl Deluxe Burger',
    available: true,
  },
  {
    id: 'bad-brambacher',
    categories: ['drinks'],
    name: 'Bad Brambacher',
    image: '/assets/dishes/bad-brambacher.png',
    imageFit: 'contain',
    description: 'Still or medium. 0.5l.',
    price: 4.8,
    currency: 'EUR',
    tags: ['non-alcoholic', 'water'],
    allergens: [],
    pairing: 'Brezn',
    available: true,
  },
  {
    id: 'table-water',
    categories: ['drinks'],
    name: 'Table water',
    image: '/assets/dishes/table-water.jpg',
    description: 'Still or sparkling.',
    price: 4.2,
    currency: 'EUR',
    sizes: [
      { label: '0.4l', price: 4.2 },
      { label: '1.0l', price: 5.9 },
    ],
    tags: ['non-alcoholic', 'water'],
    allergens: [],
    pairing: 'Bread basket',
    available: true,
  },
  {
    id: 'apple-spritzer',
    categories: ['drinks'],
    name: 'Apple spritzer',
    image: '/assets/dishes/apple-spritzer.png',
    imageFit: 'contain',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Kässpatzn',
    available: true,
  },
  {
    id: 'johannisbeerschorle',
    categories: ['drinks'],
    name: 'Johannisbeerschorle',
    image: '/assets/dishes/johannisbeerschorle.png',
    imageFit: 'contain',
    description: 'Blackcurrant spritzer. 0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Kirschmichl',
    available: true,
  },
  {
    id: 'maracujaschorle',
    categories: ['drinks'],
    name: 'Maracujaschorle',
    image: '/assets/dishes/maracujaschorle.png',
    imageFit: 'contain',
    description: 'Passion fruit spritzer. 0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Donisl Power Bowl',
    available: true,
  },
  {
    id: 'wolfra-orange-juice',
    categories: ['drinks'],
    name: 'Wolfra orange juice',
    image: '/assets/dishes/wolfra-orange-juice.png',
    imageFit: 'contain',
    description: '0.2l.',
    price: 4.5,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    pairing: 'Potato dumplings',
    available: true,
  },
  {
    id: 'espresso',
    categories: ['drinks'],
    name: 'Espresso',
    image: '/assets/dishes/espresso.png',
    description: '',
    price: 3,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    pairing: 'Apple strudel',
    available: true,
  },
  {
    id: 'double-espresso',
    categories: ['drinks'],
    name: 'Double espresso',
    image: '/assets/dishes/double-espresso.png',
    description: '',
    price: 4.5,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    pairing: 'Kaiserschmarrn (large)',
    available: true,
  },
  {
    id: 'espresso-macchiato',
    categories: ['drinks'],
    name: 'Espresso Macchiato',
    image: '/assets/dishes/espresso-macchiato.png',
    description: '',
    price: 3.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: ["dairy"],
    pairing: 'Kirschmichl',
    available: true,
  },
  {
    id: 'cappuccino',
    categories: ['drinks'],
    name: 'Cappuccino',
    image: '/assets/dishes/cappuccino.jpg',
    description: '',
    price: 4.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: ["dairy"],
    pairing: 'Crème brûlée',
    available: true,
  },
  {
    id: 'latte-macchiato',
    categories: ['drinks'],
    name: 'Latte Macchiato',
    image: '/assets/dishes/latte-macchiato.jpg',
    imageFit: 'contain',
    description: '',
    price: 4.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: ["dairy"],
    pairing: 'Apple strudel',
    available: true,
  },
  {
    id: 'milchkaffee',
    categories: ['drinks'],
    name: 'Milchkaffee',
    image: '/assets/dishes/milchkaffee.jpg',
    description: 'Coffee with milk.',
    price: 4.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: ["dairy"],
    pairing: 'Apple strudel',
    available: true,
  },
  {
    id: 'haferl-kaffee-creme',
    categories: ['drinks'],
    name: 'Mug of coffee cream',
    image: '/assets/dishes/haferl-kaffee-creme.jpg',
    description: 'Haferl Kaffee Creme.',
    price: 4.5,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: ["dairy"],
    pairing: 'Kaiserschmarrn (large)',
    available: true,
  },
  {
    id: 'drinking-chocolate',
    categories: ['drinks'],
    name: 'Drinking chocolate',
    image: '/assets/dishes/drinking-chocolate.png',
    description: 'With milk.',
    price: 4.6,
    currency: 'EUR',
    tags: ['hot-drink'],
    allergens: ["dairy"],
    pairing: 'Kirschmichl',
    available: true,
  },
  {
    id: 'tea-ronnefeldt',
    categories: ['drinks'],
    name: 'Tea (Ronnefeldt)',
    description: 'Darjeeling, Mountain herbs, Sweet Berries, Green Dragon Lung Ching, Refreshing Mint, or Fruity Camomile.',
    price: 4.8,
    currency: 'EUR',
    tags: ['hot-drink'],
    allergens: [],
    pairing: 'Apple strudel',
    available: true,
  },

  // ================= kids =================
  {
    id: 'kids-potato-dumplings',
    categories: ['kids'],
    name: 'Potato dumplings',
    image: '/assets/dishes/kids-potato-dumplings.jpg',
    description: 'With pork roast gravy.',
    price: 5.6,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten","egg"],
    pairing: 'Wolfra orange juice',
    available: true,
  },
  {
    id: 'kids-kaesspatzn',
    categories: ['kids'],
    name: 'Kässpatzn',
    image: '/assets/dishes/kids-kaesspatzn.jpg',
    description: 'Cheese spätzle, kids portion.',
    price: 7.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: ["gluten","egg","dairy"],
    pairing: 'Apple spritzer',
    available: true,
  },
  {
    id: 'kids-rostbratwuerstl',
    categories: ['kids'],
    name: '2 Rostbratwürstl',
    image: '/assets/dishes/kids-rostbratwuerstl.jpg',
    description: 'With French fries or potato-cucumber salad.',
    price: 8.9,
    currency: 'EUR',
    tags: [],
    allergens: ["gluten"],
    pairing: 'Paulaner Spezi',
    available: true,
  },
  {
    id: 'kids-fries',
    categories: ['kids'],
    name: 'Portion of French Fries',
    image: '/assets/dishes/kids-fries.jpg',
    description: '',
    price: 5.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    pairing: 'Paulaner Lemonade',
    available: true,
  },
];

export const categoryMeta: Record<MenuCategory, { icon: string }> = {
  weekly: { icon: 'CalendarDays' },
  oktoberfest: { icon: 'Tent' },
  traditional: { icon: 'UtensilsCrossed' },
  sausages: { icon: 'Ham' },
  starters: { icon: 'Salad' },
  vegan: { icon: 'Leaf' },
  desserts: { icon: 'Cake' },
  beer: { icon: 'Beer' },
  wine: { icon: 'Wine' },
  aperitif: { icon: 'Martini' },
  spirits: { icon: 'FlaskConical' },
  drinks: { icon: 'Coffee' },
  kids: { icon: 'Baby' },
};

export const categoryOrder: MenuCategory[] = [
  'weekly',
  'oktoberfest',
  'traditional',
  'sausages',
  'starters',
  'vegan',
  'desserts',
  'beer',
  'wine',
  'aperitif',
  'spirits',
  'drinks',
  'kids',
];

export function itemsByCategory(category: MenuCategory): MenuItem[] {
  return menuItems.filter((item) => item.categories.includes(category) && item.available);
}

export function findItem(id: string): MenuItem | undefined {
  return menuItems.find((item) => item.id === id);
}

/** The five weekday lunch specials, ordered Monday → Friday. */
export function weeklyLunchSpecials(): MenuItem[] {
  return menuItems
    .filter((item) => item.categories.includes('weekly') && item.weekday && item.available)
    .sort((a, b) => (a.weekday ?? 0) - (b.weekday ?? 0));
}

/**
 * The lunch special for a given JS weekday (0=Sun … 6=Sat), or undefined on
 * weekends when there is no Mittagsangebot.
 */
export function lunchSpecialForDay(jsWeekday: number): MenuItem | undefined {
  if (jsWeekday < 1 || jsWeekday > 5) return undefined;
  return menuItems.find(
    (item) => item.categories.includes('weekly') && item.weekday === jsWeekday && item.available,
  );
}

export function oktoberfestItems(): MenuItem[] {
  return itemsByCategory('oktoberfest');
}

export const featuredItemIds = [
  'schweinshaxe',
  'white-sausage',
  'kaiserschmarrn',
  'muenchner-dunkel',
  'muenchner-hell',
  'hefeweizen',
];
