import type { MenuCategory, MenuItem } from './types';

/**
 * Full menu, ported 1:1 from the real Donisl Sommerkarte (see data/menu.json
 * for the raw source with the restaurant's own 23 section headings — this
 * file just regroups the same items into the app's 11 browsing categories).
 * Allergens are left empty on purpose: the restaurant has no verified
 * per-dish allergen data, and inventing any would violate the "never
 * invent" rule the AI assistant also follows.
 *
 * The "weekly" category is ported separately from the restaurant's physical
 * Wochenkarte (weekly specials card) rather than the Sommerkarte — a rotating
 * chanterelle-season menu plus Monday-Friday lunch specials. There's no
 * day-of-week filtering in the app; each lunch special just states its day
 * in the name/description.
 */
export const menuItems: MenuItem[] = [
  // ================= weekly =================
  // -- Pfifferlinge (chanterelle season) --
  {
    id: 'chanterelle-soup',
    categories: ['weekly'],
    name: 'Pfifferlingsamtsuppe',
    description: 'Cream of chanterelle soup with a Tyrolean bacon dumpling.',
    price: 12.9,
    currency: 'EUR',
    tags: ['seasonal'],
    allergens: [],
    available: true,
  },
  {
    id: 'romaine-chanterelle-salad',
    categories: ['weekly'],
    name: 'Romanaherzen',
    description: 'Romaine lettuce hearts with raspberry vinaigrette, red onion, radish and roasted chanterelles.',
    price: 19.9,
    currency: 'EUR',
    tags: ['seasonal', 'light'],
    allergens: [],
    available: true,
  },
  {
    id: 'veal-steak-chanterelle',
    categories: ['weekly'],
    name: 'Steak vom Milchkalb',
    description: 'Veal steak with chanterelles, peas and creamed potatoes.',
    price: 35.9,
    currency: 'EUR',
    tags: ['seasonal', 'signature'],
    allergens: [],
    available: true,
  },
  {
    id: 'chanterelle-linguine',
    categories: ['weekly'],
    name: 'Pfifferling-Linguine',
    description: 'Linguine with chanterelles, cream, thyme and Bergkäse mountain cheese.',
    price: 22.9,
    currency: 'EUR',
    tags: ['seasonal', 'vegetarian'],
    allergens: [],
    available: true,
  },
  {
    id: 'chanterelle-cream',
    categories: ['weekly'],
    name: 'Pfifferlingsrahm',
    description: 'Creamed chanterelles with thyme and a pretzel dumpling.',
    price: 22.9,
    currency: 'EUR',
    tags: ['seasonal', 'vegetarian'],
    allergens: [],
    available: true,
  },
  // -- Mittagsangebot (Mon-Fri, 12:00-15:30, includes a coffee) --
  {
    id: 'lunch-monday-asparagus-linguine',
    categories: ['weekly'],
    name: 'Spargel-Linguine (Monday)',
    description: 'Weekday lunch special, served 12:00–15:30 with a coffee included. Linguine with asparagus, chive cream, roast beef and tomato.',
    price: 16,
    currency: 'EUR',
    tags: ['lunch-special'],
    allergens: [],
    available: true,
  },
  {
    id: 'lunch-tuesday-bratengroestl',
    categories: ['weekly'],
    name: 'Donisl Bratengröstl (Tuesday)',
    description: 'Weekday lunch special, served 12:00–15:30 with a coffee included. Mixed roast with white cabbage, potato dumpling and a fried egg.',
    price: 16,
    currency: 'EUR',
    tags: ['lunch-special'],
    allergens: [],
    available: true,
  },
  {
    id: 'lunch-wednesday-strindberg-steak',
    categories: ['weekly'],
    name: 'Schweinerückensteak "Strindberg" (Wednesday)',
    description: 'Weekday lunch special, served 12:00–15:30 with a coffee included. Pork loin steak with green beans and potato gratin.',
    price: 16,
    currency: 'EUR',
    tags: ['lunch-special'],
    allergens: [],
    available: true,
  },
  {
    id: 'lunch-thursday-chicken-geschnetzeltes',
    categories: ['weekly'],
    name: 'Hähnchengeschnetzeltes (Thursday)',
    description: 'Weekday lunch special, served 12:00–15:30 with a coffee included. Sliced chicken in mushroom sauce with herb spätzle.',
    price: 16,
    currency: 'EUR',
    tags: ['lunch-special'],
    allergens: [],
    available: true,
  },
  {
    id: 'lunch-friday-fish-fillet',
    categories: ['weekly'],
    name: 'Gebackenes Fischfilet (Friday)',
    description: "Weekday lunch special, served 12:00–15:30 with a coffee included. Fried catch of the day with remoulade and potato-cucumber salad.",
    price: 16,
    currency: 'EUR',
    tags: ['lunch-special'],
    allergens: [],
    available: true,
  },

  // ================= traditional =================
  // -- Traditional Bavarian Cuisine --
  {
    id: 'donisl-roasting-pan',
    categories: ['traditional'],
    name: 'Donisl roasting pan',
    description: 'Beef, duck, pork knuckle and sausages with red cabbage, potato dumplings and cheese spaetzle — for sharing.',
    price: 68,
    currency: 'EUR',
    sizes: [
      { label: '2 Pers.', price: 68 },
      { label: '4 Pers.', price: 124 },
    ],
    tags: ['sharing', 'signature'],
    allergens: [],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'roast-pork',
    categories: ['traditional'],
    name: 'Schweinebraten (roast pork)',
    description: 'Bavarian pork shoulder and belly with crackling, natural gravy, potato dumplings and coleslaw.',
    price: 16.9,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 16.9 },
      { label: 'large', price: 19.9 },
    ],
    tags: ['hearty', 'signature'],
    allergens: [],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'schweinshaxe',
    categories: ['traditional'],
    name: 'Schweinshaxe',
    description: 'Crispy roasted pork knuckle served with natural sauce, potato dumplings and coleslaw.',
    price: 23.9,
    currency: 'EUR',
    tags: ['hearty', 'signature'],
    allergens: [],
    pairing: 'Best with Dunkel beer.',
    available: true,
  },
  {
    id: 'wiener-schnitzel',
    categories: ['traditional'],
    name: 'Wiener Schnitzel',
    description: 'Bavarian straw-fed pork schnitzel with fries or potato-cucumber salad and cranberries.',
    price: 18.6,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 18.6 },
      { label: 'large', price: 22.9 },
    ],
    tags: ['classic'],
    allergens: [],
    pairing: 'Riesling Easy-White or a Radler',
    available: true,
  },
  {
    id: 'farm-duck',
    categories: ['traditional'],
    name: 'Crispy Bavarian farm duck (1/4)',
    description: 'Rosemary sauce, potato dumplings and red cabbage.',
    price: 23.5,
    currency: 'EUR',
    tags: ['hearty'],
    allergens: [],
    pairing: 'Münchner Dunkel',
    available: true,
  },
  {
    id: 'backhendl',
    categories: ['traditional'],
    name: 'Backhendl',
    description: 'Boneless breaded chicken leg with French fries or potato-cucumber salad.',
    price: 21.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'duet-of-the-ox',
    categories: ['traditional'],
    name: 'Duet of the Ox',
    description: 'Shoulder and cheek of ox, red wine jus, baby spinach, creamy potatoes.',
    price: 29.6,
    currency: 'EUR',
    tags: ['hearty'],
    allergens: [],
    available: true,
  },
  {
    id: 'veal-steak',
    categories: ['traditional'],
    name: 'Veal steak',
    description: 'Colorful peppercorn cream sauce, flamed kohlrabi, potato rösti.',
    price: 32.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'veal-meatballs',
    categories: ['traditional'],
    name: 'Veal meatballs',
    description: 'Dressed vegetables, rosemary potatoes.',
    price: 19.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  // -- Sausage Specialties --
  {
    id: 'white-sausage',
    categories: ['traditional', 'sausages'],
    name: 'White sausage (Kesselfrisch)',
    description: 'Two pieces, served with pretzel and mustard.',
    price: 10.6,
    currency: 'EUR',
    tags: ['signature'],
    allergens: [],
    available: true,
  },
  {
    id: 'white-sausage-piece',
    categories: ['traditional', 'sausages'],
    name: 'Piece of white sausage',
    description: 'A single white sausage.',
    price: 4.1,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'polish-sausage',
    categories: ['traditional', 'sausages'],
    name: 'Polish sausage',
    description: 'With pretzel and mustard.',
    price: 8.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'currywurst',
    categories: ['traditional', 'sausages'],
    name: 'Currywurst',
    description: 'Curry sausage served with French fries.',
    price: 14.9,
    currency: 'EUR',
    tags: ['classic'],
    allergens: [],
    pairing: 'Hefeweizen wheat beer',
    available: true,
  },
  {
    id: 'bratwurstreindl',
    categories: ['traditional', 'sausages'],
    name: 'Bratwurstreindl',
    description: 'Pan of grilled sausages with sauerkraut or potato salad — a sharing portion.',
    price: 17.9,
    currency: 'EUR',
    sizes: [
      { label: '4 Würstl', price: 17.9 },
      { label: '8 Würstl', price: 29 },
      { label: '16 Würstl', price: 55 },
    ],
    tags: ['sharing'],
    allergens: [],
    pairing: 'Russn (light Hefeweizen)',
    available: true,
  },
  // -- From the Grill --
  {
    id: 'rump-steak',
    categories: ['traditional'],
    name: 'Roast beef — rump steak',
    description: 'Murnau beef with red wine and onion jus, fried onions, käsespätzle.',
    price: 31.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'ribeye-300g',
    categories: ['traditional'],
    name: 'Ribeye 300 grams',
    description: 'Fat cap from Murnau beef, café de paris sauce, grilled vegetables, potato gratin.',
    price: 39.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'deluxe-burger',
    categories: ['traditional'],
    name: 'Donisl Deluxe Burger',
    description: '200g Werdenfelser beef, cheddar, lettuce, tomato, pickles, onions, homemade Donisl sauce.',
    price: 18.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    pairing: 'Münchner Hell',
    available: true,
  },
  {
    id: 'icefish',
    categories: ['traditional'],
    name: 'Icefish',
    description: 'Thyme, ratatouille vegetables, potato gratin.',
    price: 32.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },

  // ================= starters =================
  // -- Appetizers --
  {
    id: 'brotzeitbrettl',
    categories: ['starters'],
    name: 'Brotzeitbrettl',
    description: "Farmer's smoked meats, bacon sausage, liverwurst, cold roast beef, O'gmachter, mountain cheese, horseradish, bread.",
    price: 24,
    currency: 'EUR',
    sizes: [
      { label: '2 Pers.', price: 24 },
      { label: '4 Pers.', price: 42 },
    ],
    tags: ['sharing'],
    allergens: [],
    available: true,
  },
  {
    id: 'donisl-4erlei',
    categories: ['starters'],
    name: 'Donisl "4erlei"',
    description: 'Hummus, made cheese, salted butter and herbed sour cream, served with a bread basket.',
    price: 11,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
  {
    id: 'beef-tartare',
    categories: ['starters'],
    name: 'Bavarian beef tartare',
    description: 'Truffle cream, baked organic egg.',
    price: 13.4,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 13.4 },
      { label: 'large', price: 21.9 },
    ],
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'calfs-head-carpaccio',
    categories: ['starters'],
    name: "Lukewarm calf's head carpaccio",
    description: 'Pomegranate, horseradish, cucumber.',
    price: 20.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'ogmachter-kas',
    categories: ['starters'],
    name: "O'gmachter Kas",
    description: 'Creamy cheese with onion rings, radishes, lettuce and berries.',
    price: 13.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
  {
    id: 'sausage-salad',
    categories: ['starters'],
    name: 'Sausage salad from Regensburg',
    description: 'House dressing, onion rings, pickle, tomato, berry (+1.90 with strips of mountain cheese).',
    price: 15.8,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'donisl-salad',
    categories: ['starters'],
    name: 'Donisl Salad',
    description: 'Leafy greens, tomato, cucumber, house dressing, seeds and croutons.',
    price: 6.9,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 6.9 },
      { label: 'large', price: 11.9 },
    ],
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
  {
    id: 'bread-basket',
    categories: ['starters'],
    name: 'Bread basket',
    description: 'Fresh bread basket.',
    price: 4.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
  {
    id: 'brezn',
    categories: ['starters'],
    name: 'Brezn',
    description: 'Bavarian pretzel.',
    price: 2.4,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
  // -- From the Soup Kettle --
  {
    id: 'oxen-consomme',
    categories: ['starters'],
    name: 'Oxen consommé',
    description: 'Clear beef broth with liver dumplings or pancake strips, vegetables and chives.',
    price: 7.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'tomato-soup',
    categories: ['starters'],
    name: 'Velvet soup from bush tomato',
    description: 'Smooth tomato soup with a burrata-basil cream.',
    price: 9.9,
    currency: 'EUR',
    tags: ['vegan'],
    allergens: [],
    available: true,
  },
  // -- Extra Side Dishes --
  {
    id: 'classic-sides',
    categories: ['starters'],
    name: 'Classic side dish',
    description: 'Sauerkraut, red cabbage, bacon and cabbage salad, creamy potatoes, potato dumplings, small roasted potatoes, spätzle or French fries — each.',
    price: 5.6,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'vegetable-sides',
    categories: ['starters'],
    name: 'Vegetable side dish',
    description: 'Vegetable side dish or potato and cucumber salad — each.',
    price: 5.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },

  // ================= vegan =================
  {
    id: 'power-bowl',
    categories: ['vegan'],
    name: 'Donisl Power Bowl',
    description: 'Fragrant rice, avocado, edamame, chickpeas, carrots, tomato, cucumber, peanuts, orange-mint-lime dressing.',
    price: 20.9,
    currency: 'EUR',
    sizes: [
      { label: 'with chicken', price: 20.9 },
      { label: 'with cured salmon', price: 21.9 },
      { label: 'with goat cheese', price: 20.9 },
    ],
    tags: ['bowl', 'signature'],
    allergens: [],
    available: true,
  },
  {
    id: 'kaesespaetzle',
    categories: ['vegan'],
    name: 'Käsespätzle',
    description: 'Cheese spätzle with onion rings.',
    price: 14.6,
    currency: 'EUR',
    sizes: [
      { label: 'small', price: 14.6 },
      { label: 'large', price: 17.6 },
    ],
    tags: ['vegetarian'],
    allergens: [],
    pairing: 'Münchner Dunkel or a full-bodied white wine',
    available: true,
  },
  {
    id: 'linguine-truffles',
    categories: ['vegan'],
    name: 'Linguine with truffles',
    description: 'Pasta with baby spinach and winter truffle.',
    price: 22.9,
    currency: 'EUR',
    tags: ['vegan'],
    allergens: [],
    available: true,
  },
  {
    id: 'rahmschwammerl',
    categories: ['vegan'],
    name: 'Rahmschwammerl',
    description: 'Creamy mushrooms served with pretzel dumplings.',
    price: 17.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },

  // ================= desserts =================
  {
    id: 'creme-brulee',
    categories: ['desserts'],
    name: 'Crème brûlée',
    description: 'Served with sorbet and berries.',
    price: 9.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    pairing: 'Rieslaner Auslese dessert wine',
    available: true,
  },
  {
    id: 'kaiserschmarrn',
    categories: ['desserts'],
    name: 'Kaiserschmarrn (large)',
    description: 'Raisins, butter, sugar and caramelized almonds, served with applesauce — ideal for sharing.',
    price: 15.6,
    currency: 'EUR',
    tags: ['vegetarian', 'sharing', 'signature'],
    allergens: [],
    pairing: 'Rieslaner Auslese dessert wine',
    available: true,
  },
  {
    id: 'kirschmichl',
    categories: ['desserts'],
    name: 'Kirschmichl',
    description: 'Warm cherry cake served with custard.',
    price: 9.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
  {
    id: 'apple-strudel',
    categories: ['desserts'],
    name: 'Apple strudel',
    description: 'Classic apple strudel served with custard.',
    price: 9.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    pairing: 'Milchkaffee',
    available: true,
  },

  // ================= beer =================
  {
    id: 'muenchner-hell',
    categories: ['beer'],
    name: 'Münchner Hell',
    description: 'Bottom-fermented, delicately bitter hop note, slightly malty. 5.0% vol.',
    price: 4.6,
    currency: 'EUR',
    sizes: [
      { label: '0.35l', price: 4.6 },
      { label: '0.5l', price: 5.2 },
      { label: '1.0l', price: 10.4 },
    ],
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'beer-light-alcohol-free',
    categories: ['beer'],
    name: 'Light Alcohol-Free',
    description: 'Naturally cloudy, caramel and honey notes. <0.5% vol.',
    price: 5.2,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'muenchner-radler',
    categories: ['beer'],
    name: 'Münchner Radler',
    description: 'Munich Helles with fine lemonade, not too sweet.',
    price: 5.2,
    currency: 'EUR',
    tags: ['light'],
    allergens: [],
    available: true,
  },
  {
    id: 'muenchner-dunkel',
    categories: ['beer'],
    name: 'Münchner Dunkel',
    description: 'Delicately bitter, roasted malt with caramel and candied fruit notes. 5.0% vol.',
    price: 6.1,
    currency: 'EUR',
    tags: ['hearty'],
    allergens: [],
    available: true,
  },
  {
    id: 'hefeweizen',
    categories: ['beer'],
    name: 'Hefeweizen (Yeast White)',
    description: 'Top-fermented wheat beer with banana and honey notes.',
    price: 6.2,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'russn',
    categories: ['beer'],
    name: 'Russn',
    description: 'Hefeweizen with delicate lemonade, not too sweet.',
    price: 6.2,
    currency: 'EUR',
    tags: ['light'],
    allergens: [],
    available: true,
  },
  {
    id: 'cola-wheat',
    categories: ['beer'],
    name: 'Cola Wheat',
    description: 'Hefeweizen with Coca-Cola.',
    price: 6.2,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'non-alcoholic-wheat',
    categories: ['beer'],
    name: 'Paulaner alcohol-free wheat beer',
    description: 'Gently dealcoholized after full maturation, keeps its aroma.',
    price: 6.2,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'salvator',
    categories: ['beer'],
    name: 'Salvator',
    description: 'Strong beer (Starkbier), seasonal — available February/March. 0.5l.',
    price: 6.4,
    currency: 'EUR',
    tags: ['seasonal', 'strong'],
    allergens: [],
    available: true,
  },
  {
    id: 'kellerbier',
    categories: ['beer'],
    name: 'Kellerbier',
    description: 'Seasonal — available June/July/August (Sommerzeit). 0.5l.',
    price: 6.1,
    currency: 'EUR',
    tags: ['seasonal'],
    allergens: [],
    available: true,
  },
  {
    id: 'wiesnbier',
    categories: ['beer'],
    name: 'Wiesnbier',
    description: 'Oktoberfest beer, seasonal — available September/October. 0.5l.',
    price: 6.4,
    currency: 'EUR',
    tags: ['seasonal'],
    allergens: [],
    available: true,
  },

  // ================= wine =================
  // -- Wine from the Barrel (by the glass) --
  {
    id: 'weissweinschorle',
    categories: ['wine'],
    name: 'Weissweinschorle',
    description: 'White wine spritzer. 0.3l.',
    price: 6,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: [],
    available: true,
  },
  {
    id: 'pinot-gris-glass',
    categories: ['wine'],
    name: 'Pinot Gris (by the glass)',
    description: 'Hirschmüller Winery, Württemberg — light, easy-drinking.',
    price: 6,
    currency: 'EUR',
    sizes: [
      { label: '0.1l', price: 6 },
      { label: '0.2l', price: 9 },
    ],
    tags: ['white', 'by-glass'],
    allergens: [],
    available: true,
  },
  {
    id: 'primitivo-glass',
    categories: ['wine'],
    name: 'Primitivo Puglia IGT (by the glass)',
    description: 'Sir of the Faun, Puglia — dark berries, cherry, subtle spice.',
    price: 6,
    currency: 'EUR',
    sizes: [
      { label: '0.1l', price: 6 },
      { label: '0.2l', price: 9 },
    ],
    tags: ['red', 'by-glass'],
    allergens: [],
    available: true,
  },
  {
    id: 'prodry-frizzante',
    categories: ['wine'],
    name: 'Prodry Frizzante',
    description: 'Motelvini, Veneto, Italy. 0.1l.',
    price: 4.6,
    currency: 'EUR',
    tags: ['sparkling', 'by-glass'],
    allergens: [],
    available: true,
  },
  // -- Champagne & Sparkling --
  {
    id: 'paul-michel-champagne',
    categories: ['wine'],
    name: 'Paul Michel',
    description: 'Champagne Premier Cru, Champagne, France. 0.75l bottle.',
    price: 120,
    currency: 'EUR',
    tags: ['sparkling', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'taittinger-rose',
    categories: ['wine'],
    name: 'Taittinger Prestige Rosé Brut',
    description: 'Champagne Taittinger, France. 0.75l bottle.',
    price: 145,
    currency: 'EUR',
    tags: ['sparkling', 'rose', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'valdo-prosecco',
    categories: ['wine'],
    name: 'Valdo Prosecco Superiore DOCG',
    description: 'Valdo, Veneto — classic Italian sparkling wine. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['sparkling', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'winzersekt',
    categories: ['wine'],
    name: 'Winzersekt',
    description: 'Pfaffmann Winery, Palatinate, Germany. 0.75l bottle.',
    price: 45,
    currency: 'EUR',
    tags: ['sparkling', 'bottle'],
    allergens: [],
    available: true,
  },
  // -- White Wine --
  {
    id: 'chardonnay-bottle',
    categories: ['wine'],
    name: 'Chardonnay',
    description: 'Hirschmüller Winery, Württemberg — passion fruit, mango, pineapple. 0.75l bottle.',
    price: 34,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'chardonnay-glass',
    categories: ['wine'],
    name: 'Chardonnay (by the glass)',
    description: 'Hirschmüller Winery, Württemberg. 0.1l.',
    price: 6,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: [],
    available: true,
  },
  {
    id: 'chardonnay-macon-ige',
    categories: ['wine'],
    name: 'Chardonnay Mâcon-Igé La Cra',
    description: 'Domaine Fichet, Burgundy — apple, pear, white peach, subtle minerality. 0.75l bottle.',
    price: 69,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'pinot-gris-tradition',
    categories: ['wine'],
    name: 'Pinot Gris Tradition',
    description: 'Bott Frères Winery, Burgundy — apricot, Viennese apple, hazelnut, subtle smoke. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'pinot-gris-oetinger',
    categories: ['wine'],
    name: 'Pinot Gris',
    description: 'Oetinger Winery, Rheingau — ripe pear, yellow apple, hint of almond. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'pinot-gris-reserve-pauline',
    categories: ['wine'],
    name: 'Pinot Gris Reserve Pauline',
    description: 'Pfaffmann Winery, Palatinate — pear, pineapple, nectarine, lemongrass, floral. 0.75l bottle.',
    price: 56,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'pinot-blanc-grand-reserve',
    categories: ['wine'],
    name: 'Pinot Blanc Grand Reserve',
    description: 'Taubenschuss Winery, Austrian Weinviertel — melon, hazelnut, hay, caramel. 0.75l bottle.',
    price: 79,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'trebbiano-di-lugana',
    categories: ['wine'],
    name: 'Trebbiano di Lugana',
    description: 'Zenato Winery, Veneto, Italy — fresh acidity, mineral, citrus, green apple, pear. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'lugana-glass',
    categories: ['wine'],
    name: 'Lugana (by the glass)',
    description: 'Zenato Winery, Veneto, Italy. 0.1l.',
    price: 6.5,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: [],
    available: true,
  },
  {
    id: 'riesling-easy-white',
    categories: ['wine'],
    name: 'Riesling Easy-White',
    description: 'Oetinger Winery, Rheingau — lime, apple, white peach, ideal aperitif. 0.75l bottle.',
    price: 33,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    pairing: 'Wiener Schnitzel',
    available: true,
  },
  {
    id: 'riesling-gottloos',
    categories: ['wine'],
    name: 'Riesling Gottloos',
    description: 'Dr. Loosen Winery, Mosel — citrus, apple, elegant minerality. 0.75l bottle.',
    price: 42,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'riesling-heiligenstein',
    categories: ['wine'],
    name: 'Riesling Ried Heiligenstein',
    description: 'Bründlmayer Winery, Langenlois, Kamptal, Austria — fresh citrus, apple, herbal spice. 0.75l bottle.',
    price: 98,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'riesling-smoky-dry',
    categories: ['wine'],
    name: 'Riesling Smoky Dry',
    description: 'Weingut Oetinger, Rheingau — smoky minerality, juicy apple, citrus. 0.75l bottle.',
    price: 49,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'riesling-bright-side-of-life',
    categories: ['wine'],
    name: 'Riesling Refill "Bright side of life" 2024',
    description: 'Stahl Winery, Franconia, Germany — fruity, fresh, uncomplicated. 0.75l bottle.',
    price: 29,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'riesling-nachschlag-glass',
    categories: ['wine'],
    name: 'Riesling "Nachschlag – Bright Side of Life" 2024 (by the glass)',
    description: 'Stahl Winery, Franconia, Germany. 0.1l.',
    price: 5.5,
    currency: 'EUR',
    tags: ['white', 'by-glass'],
    allergens: [],
    available: true,
  },
  {
    id: 'sauvignon-blanc',
    categories: ['wine'],
    name: 'Sauvignon Blanc',
    description: 'Chateau de la Chaise, Loire — gooseberry, green apple, exotic fruit. 0.75l bottle.',
    price: 45,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'sauvignon-blanc-reserve',
    categories: ['wine'],
    name: 'Sauvignon Blanc Reserve -S-',
    description: 'Taubenschuss Winery, Austrian Weinviertel — lime, gooseberry, exotic fruit. 0.75l bottle.',
    price: 58,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'silvaner-easy-white',
    categories: ['wine'],
    name: 'Silvaner Easy-White',
    description: 'Weingut am Stein, Franconia — green apple, pear, subtle herbs. 0.75l bottle.',
    price: 32,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'gruener-veltliner-tenn',
    categories: ['wine'],
    name: 'Grüner Veltliner Ried Tenn DAC Reserve',
    description: 'Taubenschuss Winery, Austrian Weinviertel — apple, white pepper, herbal spice. 0.75l bottle.',
    price: 54,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  // -- Large Bottles --
  {
    id: 'riesling-gottloos-3l',
    categories: ['wine'],
    name: 'Riesling Gottloos (large bottle)',
    description: 'Dr. Loosen Winery, Mosel. 3.0l bottle.',
    price: 168,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'gruener-veltliner-steinberg',
    categories: ['wine'],
    name: 'Grüner Veltliner Ried Steinberg',
    description: 'Karl Fritsch Winery, Burgenland, Austria. 1.5l bottle.',
    price: 120,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'chardonnay-morillon',
    categories: ['wine'],
    name: 'Chardonnay Morillon Ried Flammberg',
    description: 'Lackner-Tinnacher Winery, Southern Styria, Austria. 1.5l bottle.',
    price: 160,
    currency: 'EUR',
    tags: ['white', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'cuvee-adrian-sangiovese',
    categories: ['wine'],
    name: 'Cuvée Adrian Sangiovese 2021',
    description: 'Red cuvée, Toscana Rosso, Tuscany. 1.5l bottle.',
    price: 98,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  // -- Red Wine --
  {
    id: 'primitivo-bottle',
    categories: ['wine'],
    name: 'Primitivo Puglia IGT',
    description: 'Barbanera Winery, Apulia, Italy — dark berries, cherry, subtle spice. 0.75l bottle.',
    price: 34,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'herrgott-cuvee',
    categories: ['wine'],
    name: 'Herrgott Cuvée',
    description: 'Cabernet Sauvignon/Franc, Merlot, Weingut am Nil, Palatinate — cherries, red berries. 0.75l bottle.',
    price: 38,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'herrgott-cuvee-glass',
    categories: ['wine'],
    name: 'Herrgott Cuvée (by the glass)',
    description: 'Cabernet Sauvignon/Franc, Merlot, Weingut am Nil, Palatinate. 0.1l.',
    price: 6.5,
    currency: 'EUR',
    tags: ['red', 'by-glass'],
    allergens: [],
    available: true,
  },
  {
    id: 'tuscany-red-cuvee',
    categories: ['wine'],
    name: 'Tuscany Red Cuvée',
    description: 'Duca di Salangane, Toscana — cherries, dark berries. 0.75l bottle.',
    price: 29,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'pinot-noir-goldberg',
    categories: ['wine'],
    name: 'Pinot Noir Ried Goldberg',
    description: 'Toni Hartl Winery, Burgenland — red berries, cherries, subtle spice. 0.75l bottle.',
    price: 79,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'merlot',
    categories: ['wine'],
    name: 'Merlot',
    description: 'Chateau Gensac, Gascony — dark cherries, plums, spice. 0.75l bottle.',
    price: 42,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'brunello-di-montalcino',
    categories: ['wine'],
    name: 'Brunello di Montalcino DOCG',
    description: 'Tenuta Corte Pavone Winery, Sangiovese, Tuscany — dark berry, cherry, chocolate. 0.75l bottle.',
    price: 135,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'black-ox-cuvee',
    categories: ['wine'],
    name: 'Black OX Cuvée',
    description: 'Cabernet Sauvignon, Dornfelder, Tempranillo, Weingut Lergenmüller, Palatinate — dark berries, cherry, spice. 0.75l bottle.',
    price: 39,
    currency: 'EUR',
    tags: ['red', 'bottle'],
    allergens: [],
    available: true,
  },
  // -- Rosé Wine --
  {
    id: 'rose-lime-stone',
    categories: ['wine'],
    name: 'Rosé Lime & Stone',
    description: 'Unger Winery, Lake Neusiedl — red berries, strawberry, raspberry, citrus. 0.75l bottle.',
    price: 36,
    currency: 'EUR',
    tags: ['rose', 'bottle'],
    allergens: [],
    available: true,
  },
  {
    id: 'torres-natureo',
    categories: ['wine'],
    name: 'Torres Natureo (alcohol-free)',
    description: 'Miguel Torres, Vilafranca del Penedès — citrus, apple, light. 0.75l bottle.',
    price: 29,
    currency: 'EUR',
    tags: ['rose', 'bottle', 'non-alcoholic'],
    allergens: [],
    available: true,
  },
  // -- Dessert Wine --
  {
    id: 'rieslaner-auslese',
    categories: ['wine'],
    name: 'Rieslaner Auslese',
    description: 'Juliusspital Winery, Franconia — dessert wine. 0.5l bottle.',
    price: 58,
    currency: 'EUR',
    tags: ['dessert-wine', 'bottle'],
    allergens: [],
    pairing: 'Kaiserschmarrn or Crème brûlée',
    available: true,
  },

  // ================= aperitif =================
  {
    id: 'aperol-spritz',
    categories: ['aperitif'],
    name: 'Aperol Spritz',
    description: 'Classic Italian aperitif. 0.2l.',
    price: 8.9,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: [],
    available: true,
  },
  {
    id: 'hugo',
    categories: ['aperitif'],
    name: 'Hugo',
    description: 'Elderflower spritz. 0.2l.',
    price: 8.9,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: [],
    available: true,
  },
  {
    id: 'campari-soda',
    categories: ['aperitif'],
    name: 'Campari Soda',
    description: '0.2l.',
    price: 6,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: [],
    available: true,
  },
  {
    id: 'campari-orange',
    categories: ['aperitif'],
    name: 'Campari Orange',
    description: '0.2l.',
    price: 8.4,
    currency: 'EUR',
    tags: ['aperitif'],
    allergens: [],
    available: true,
  },
  {
    id: 'sanbitter',
    categories: ['aperitif'],
    name: 'Sanbitter',
    description: 'Alcohol-free bitter aperitif. 0.2l.',
    price: 8,
    currency: 'EUR',
    tags: ['aperitif', 'non-alcoholic'],
    allergens: [],
    available: true,
  },

  // ================= spirits =================
  {
    id: 'nut-in-a-bottle',
    categories: ['spirits'],
    name: 'Nut (in a bottle)',
    description: '2cl.',
    price: 4,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'ruescherl',
    categories: ['spirits'],
    name: 'Rüscherl',
    description: '13cl.',
    price: 5,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'hirschkuss',
    categories: ['spirits'],
    name: 'Hirschkuss',
    description: '38% vol., swing-top bottle, 4cl.',
    price: 7,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'vodka-redbull',
    categories: ['spirits'],
    name: 'Vodka RedBull',
    description: '0.27l.',
    price: 9.5,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'williams-christ-pear',
    categories: ['spirits'],
    name: 'Williams Christ pear',
    description: '40% vol. Edelbrand, Sigi Herzog Distillate. 2cl.',
    price: 4.9,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'farm-fruit-growers',
    categories: ['spirits'],
    name: 'Farm fruit growers',
    description: 'Linster fine fruit distillery, aged 1 year in oak barrels. 2cl.',
    price: 4.6,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'feiner-mirabell',
    categories: ['spirits'],
    name: 'Feiner Mirabell',
    description: 'Linster fine fruit distillery, ripe apricot flavor. 2cl.',
    price: 5.6,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'enzian-gentian-brandy',
    categories: ['spirits'],
    name: 'Enzian Gentian Brandy',
    description: 'Wilhelm Marx Fine Spirits Manufactory. 2cl.',
    price: 7.9,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'raspberry-pulp-brandy',
    categories: ['spirits'],
    name: 'Raspberry pulp brandy',
    description: '40% vol. Edelmanufaktur Wilhelm Marx. 2cl.',
    price: 7.9,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },
  {
    id: 'grappa-chardonnay',
    categories: ['spirits'],
    name: 'Grappa from Chardonnay',
    description: 'Grandfather. 2cl.',
    price: 5.6,
    currency: 'EUR',
    tags: ['spirit'],
    allergens: [],
    available: true,
  },

  // ================= drinks (alcohol-free & coffee) =================
  {
    id: 'paulaner-spezi',
    categories: ['drinks'],
    name: 'Paulaner Spezi',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'coca-cola',
    categories: ['drinks'],
    name: 'Coca-Cola',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'coca-cola-zero',
    categories: ['drinks'],
    name: 'Coca-Cola Zero',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'paulaner-lemonade',
    categories: ['drinks'],
    name: 'Paulaner Lemonade',
    description: '0.33l.',
    price: 4.2,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'paulaner-orange-lemonade',
    categories: ['drinks'],
    name: 'Paulaner Orange Lemonade',
    description: '0.33l.',
    price: 4.2,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'tonic',
    categories: ['drinks'],
    name: 'Tonic',
    description: '0.2l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'red-bull',
    categories: ['drinks'],
    name: 'Red Bull',
    description: '0.25l.',
    price: 5.5,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'bad-brambacher',
    categories: ['drinks'],
    name: 'Bad Brambacher',
    description: 'Still or medium. 0.5l.',
    price: 4.8,
    currency: 'EUR',
    tags: ['non-alcoholic', 'water'],
    allergens: [],
    available: true,
  },
  {
    id: 'table-water',
    categories: ['drinks'],
    name: 'Table water',
    description: 'Still or sparkling.',
    price: 4.2,
    currency: 'EUR',
    sizes: [
      { label: '0.4l', price: 4.2 },
      { label: '1.0l', price: 6.9 },
    ],
    tags: ['non-alcoholic', 'water'],
    allergens: [],
    available: true,
  },
  {
    id: 'apple-spritzer',
    categories: ['drinks'],
    name: 'Apple spritzer',
    description: '0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'johannisbeerschorle',
    categories: ['drinks'],
    name: 'Johannisbeerschorle',
    description: 'Blackcurrant spritzer. 0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'maracujaschorle',
    categories: ['drinks'],
    name: 'Maracujaschorle',
    description: 'Passion fruit spritzer. 0.4l.',
    price: 4.9,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'wolfra-orange-juice',
    categories: ['drinks'],
    name: 'Wolfra orange juice',
    description: '0.2l.',
    price: 4.5,
    currency: 'EUR',
    tags: ['non-alcoholic'],
    allergens: [],
    available: true,
  },
  {
    id: 'espresso',
    categories: ['drinks'],
    name: 'Espresso',
    description: '',
    price: 3,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    available: true,
  },
  {
    id: 'double-espresso',
    categories: ['drinks'],
    name: 'Double espresso',
    description: '',
    price: 4.5,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    available: true,
  },
  {
    id: 'espresso-macchiato',
    categories: ['drinks'],
    name: 'Espresso Macchiato',
    description: '',
    price: 3.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    available: true,
  },
  {
    id: 'cappuccino',
    categories: ['drinks'],
    name: 'Cappuccino',
    description: '',
    price: 4.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    available: true,
  },
  {
    id: 'latte-macchiato',
    categories: ['drinks'],
    name: 'Latte Macchiato',
    description: '',
    price: 4.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    available: true,
  },
  {
    id: 'milchkaffee',
    categories: ['drinks'],
    name: 'Milchkaffee',
    description: 'Coffee with milk.',
    price: 4.7,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    available: true,
  },
  {
    id: 'haferl-kaffee-creme',
    categories: ['drinks'],
    name: 'Mug of coffee cream',
    description: 'Haferl Kaffee Creme.',
    price: 4.5,
    currency: 'EUR',
    tags: ['coffee'],
    allergens: [],
    available: true,
  },
  {
    id: 'drinking-chocolate',
    categories: ['drinks'],
    name: 'Drinking chocolate',
    description: 'With milk.',
    price: 4.6,
    currency: 'EUR',
    tags: ['hot-drink'],
    allergens: [],
    available: true,
  },
  {
    id: 'tea-ronnefeldt',
    categories: ['drinks'],
    name: 'Tea (Ronnefeldt)',
    description: 'Darjeeling, Mountain herbs, Sweet Berries, Green Dragon Lung Ching, Refreshing Mint, or Fruity Camomile.',
    price: 4.8,
    currency: 'EUR',
    tags: ['hot-drink'],
    allergens: [],
    available: true,
  },

  // ================= kids =================
  {
    id: 'kids-potato-dumplings',
    categories: ['kids'],
    name: 'Potato dumplings',
    description: 'With pork roast gravy.',
    price: 5.6,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'kids-kaesspatzn',
    categories: ['kids'],
    name: 'Kässpatzn',
    description: 'Cheese spätzle, kids portion.',
    price: 7.9,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
  {
    id: 'kids-rostbratwuerstl',
    categories: ['kids'],
    name: '2 Rostbratwürstl',
    description: 'With French fries or potato-cucumber salad.',
    price: 8.9,
    currency: 'EUR',
    tags: [],
    allergens: [],
    available: true,
  },
  {
    id: 'kids-fries',
    categories: ['kids'],
    name: 'Portion of French Fries',
    description: '',
    price: 5.6,
    currency: 'EUR',
    tags: ['vegetarian'],
    allergens: [],
    available: true,
  },
];

export const categoryMeta: Record<MenuCategory, { icon: string }> = {
  weekly: { icon: 'CalendarDays' },
  traditional: { icon: 'UtensilsCrossed' },
  sausages: { icon: 'Ham' },
  starters: { icon: 'Salad' },
  vegan: { icon: 'Leaf' },
  desserts: { icon: 'Cake' },
  beer: { icon: 'Beer' },
  wine: { icon: 'Wine' },
  aperitif: { icon: 'Martini' },
  spirits: { icon: 'FlaskConical' },
  drinks: { icon: 'Coffee' },
  kids: { icon: 'Baby' },
};

export const categoryOrder: MenuCategory[] = [
  'weekly',
  'traditional',
  'sausages',
  'starters',
  'vegan',
  'desserts',
  'beer',
  'wine',
  'aperitif',
  'spirits',
  'drinks',
  'kids',
];

export function itemsByCategory(category: MenuCategory): MenuItem[] {
  return menuItems.filter((item) => item.categories.includes(category) && item.available);
}

export function findItem(id: string): MenuItem | undefined {
  return menuItems.find((item) => item.id === id);
}

export const featuredItemIds = ['schweinshaxe', 'white-sausage', 'kaiserschmarrn', 'muenchner-dunkel'];
